server:
  port: 1010
spring:
#  http:
#    encoding:
#      force: true
#      charset: UTF-8
  application:
    name: cloud-admin-server
#  freemarker:
#    request-context-attribute: req
#    #prefix: /templates/
#    suffix: .html
#    content-type: text/html
#    enabled: true
#    cache: false
#    charset: UTF-8
#    allow-request-override: false
#    expose-request-attributes: true
#    expose-session-attributes: true
#    expose-spring-macro-helpers: true
#    #template-loader-path: classpath:/templates/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/hq_account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat,wall,log4j
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1000/eureka/
  instance:
    ip-address: ture

#mybatis-plus:
#  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
#  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
#  mapper-locations: classpath:/mappers/*Mapper.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.cloud.hq.business.model
#  global-config:
#    db-config:
#      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#      id-type: AUTO
#      #驼峰下划线转换
#      table-underline: true
#      #mp2.3+ 全局表前缀 mp_
#      #table-prefix: mp_
#      #刷新mapper 调试神器
#      #refresh-mapper: true
#      #数据库大写下划线转换
#      #capital-mode: true
#      # Sequence序列接口实现类配置
#      #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
#      #逻辑删除配置（下面3个配置）
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#      #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
#      #自定义填充策略接口实现
#    #meta-object-handler: com.baomidou.mybatisplus.core.handlers.MetaObjectHandler
#  configuration:
#    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#    #配置JdbcTypeForNull, oracle数据库必须配置
#    #jdbc-type-for-null: 'null'

