server:
  port: 1011
spring:
  application:
    name: cloud-business-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/hq_account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat,wall,log4j
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1000/eureka/
  instance:
    ip-address: ture